// Regenerates js/data/demo-results.js from ../demo/results.json (the head-to-head run on anvil).
// Run from web/:  node tools/snapshot-demo.mjs
import { readFileSync, writeFileSync } from "node:fs";

const r = JSON.parse(readFileSync(new URL("../../demo/results.json", import.meta.url)));
// Rounded to nearest at d decimals (via micro-units), matching how the demo prints its numbers.
const n = (wei, d = 4) => Math.round(Number(BigInt(wei) / 10n ** 12n) / 10 ** (6 - d)) / 10 ** d;

const people = r.participants.map((p) => ({
  name: p.bot ? "BOT" : p.name.toUpperCase(),
  bot: p.bot,
  arrival: p.arrival,
  maxPrice: n(p.maxPrice, 3),
  curve: { status: p.curve.status, block: p.curve.block, tokens: n(p.curve.tokens, 1), paid: n(p.curve.paid, 2), avg: n(p.curve.avgPrice, 3) },
  auction: { status: p.auction.status, bidPrice: n(p.auction.bidPrice, 3), bidAmount: n(p.auction.bidAmount, 1), tokens: n(p.auction.allocated, 1), paid: n(p.auction.paid, 2), avg: n(p.auction.pricePerToken, 3) },
}));

const snap = {
  source: "demo/results.json: RunScenario.s.sol on a local anvil chain",
  transactions: r.meta.transactions,
  supply: n(r.meta.supply, 0),
  crowd: r.meta.crowd,
  curve: {
    openPrice: n(r.curve.openPrice, 3),
    finalSpot: n(r.curve.finalSpot, 3),
    botAvg: n(r.curve.bot.avgPrice, 3),
    crowdAvg: n(r.curve.crowd.avgPrice, 3),
    botShare: Number(BigInt(r.curve.bot.tokens) * 1000n / BigInt(r.curve.sold)) / 10,
    fills: r.curve.fills.map((f) => ({ who: f.bot ? "BOT" : f.who.toUpperCase(), bot: f.bot, block: f.block, tokens: n(f.tokens, 1), avg: Number(BigInt(f.paid) * 1000n / BigInt(f.tokens)) / 1000 })),
    emptyHanded: people.filter((p) => !p.bot && p.curve.status !== "filled").length,
  },
  auction: {
    clearing: n(r.auction.clearingPrice, 3),
    sold: n(r.auction.sold, 0),
    demand: n(r.auction.demand, 1),
    lpTokens: n(r.auction.lpTokens, 0),
    lpMon: n(r.auction.lpMon, 2),
    lpLocked: r.auction.lpLocked,
  },
  people,
};

writeFileSync(new URL("../js/data/demo-results.js", import.meta.url),
  `// Generated by web/tools/snapshot-demo.mjs from ${snap.source}. Do not edit by hand.\nexport default ${JSON.stringify(snap, null, 1)};\n`);
console.log(`wrote js/data/demo-results.js: ${people.length} participants, clearing ${snap.auction.clearing}, bot ${snap.curve.botAvg} vs crowd ${snap.curve.crowdAvg}`);
