// Summarises demo/fairness.json (written by script/FairnessStats.s.sol) into headline fairness
// numbers, prints a markdown table, and writes web/js/data/fairness.js for the landing page.
// Run from demo/: node tools/fairness-summary.mjs
import { readFileSync, writeFileSync } from "node:fs";

const raw = JSON.parse(readFileSync("fairness.json", "utf8"));
const L = Object.values(raw);
const n = L.length;
const num = (v) => Number(BigInt(v)) / 1e18;
const q = (arr, p) => { const s = [...arr].sort((a, b) => a - b); return s[Math.min(s.length - 1, Math.floor(p * (s.length - 1) + 0.5))]; };
const stat = (arr) => ({ median: q(arr, 0.5), p10: q(arr, 0.1), p90: q(arr, 0.9), mean: arr.reduce((a, b) => a + b, 0) / arr.length });
const r2 = (x) => Math.round(x * 100) / 100;

const withBoth = L.filter((l) => num(l.curveBotAvg) > 0 && num(l.curveCrowdAvg) > 0);
const crowdOverBot = withBoth.map((l) => num(l.curveCrowdAvg) / num(l.curveBotAvg));
const botCheaper = withBoth.filter((l) => num(l.curveBotAvg) < num(l.curveCrowdAvg)).length;
const spread = L.filter((l) => num(l.curveMinBuyerAvg) > 0).map((l) => num(l.curveMaxBuyerAvg) / num(l.curveMinBuyerAvg));
const botShareCurve = L.map((l) => Number(l.curveBotShareBps) / 100);
const botShareEven = L.map((l) => Number(l.evenBotShareBps) / 100);
const interested = L.reduce((a, l) => a + Number(l.interested), 0);
const shutCurve = L.reduce((a, l) => a + Number(l.curveShutOut), 0);
const shutEven = L.reduce((a, l) => a + Number(l.evenShutOut), 0);
const lateNothing = L.filter((l) => num(l.curveLateAvg) === 0).length;
const crowdOverFair = L.filter((l) => num(l.curveCrowdAvg) > 0).map((l) => num(l.curveCrowdAvg) / num(l.clearing));
const maxDev = L.reduce((a, l) => (BigInt(l.evenMaxPriceDeviationWei) > a ? BigInt(l.evenMaxPriceDeviationWei) : a), 0n);

const s = {
  launches: n,
  crowdSize: { min: Math.min(...L.map((l) => Number(l.crowd))), max: Math.max(...L.map((l) => Number(l.crowd))) },
  curve: {
    crowdPaysTimesBot: stat(crowdOverBot),
    botCheaperPct: (100 * botCheaper) / withBoth.length,
    priceSpread: stat(spread),
    botShare: stat(botShareCurve),
    shutOutPct: (100 * shutCurve) / interested,
    lateThirdGotNothingPct: (100 * lateNothing) / n,
    crowdPaysTimesFair: stat(crowdOverFair),
  },
  even: {
    crowdPaysTimesBot: 1,
    priceSpread: 1,
    botShare: stat(botShareEven),
    shutOutPct: (100 * shutEven) / interested,
    maxPriceDeviationWei: maxDev.toString(),
  },
  source: "demo/script/FairnessStats.s.sol on the real AuctionEngine and a local bonding curve, in memory",
};
writeFileSync("../web/js/data/fairness.js", `// Generated by demo/tools/fairness-summary.mjs from demo/fairness.json. Do not edit.\nexport default ${JSON.stringify(s, null, 2)};\n`);

const pct = (x) => `${r2(x)}%`;
console.log(`Launches: ${n} (crowd ${s.crowdSize.min}–${s.crowdSize.max} buyers each, plus one sniper bot)\n`);
console.log("| Measure | Bonding curve (median, p10–p90) | Even |");
console.log("| --- | --- | --- |");
console.log(`| Crowd's price ÷ bot's price | ${r2(s.curve.crowdPaysTimesBot.median)}× (${r2(s.curve.crowdPaysTimesBot.p10)}–${r2(s.curve.crowdPaysTimesBot.p90)}×) | 1× (everyone pays the same price) |`);
console.log(`| Launches where the bot paid less than the crowd | ${pct(s.curve.botCheaperPct)} | 0% |`);
console.log(`| Highest ÷ lowest price paid by buyers | ${r2(s.curve.priceSpread.median)}× (${r2(s.curve.priceSpread.p10)}–${r2(s.curve.priceSpread.p90)}×) | 1× (largest gap: ${s.even.maxPriceDeviationWei} wei of rounding) |`);
console.log(`| Bot's share of the supply | ${r2(s.curve.botShare.median)}% (${r2(s.curve.botShare.p10)}–${r2(s.curve.botShare.p90)}%) | ${r2(s.even.botShare.median)}% (${r2(s.even.botShare.p10)}–${r2(s.even.botShare.p90)}%) |`);
console.log(`| Buyers willing to pay the fair price who got nothing | ${pct(s.curve.shutOutPct)} | ${pct(s.even.shutOutPct)} |`);
console.log(`| Launches where the last third of arrivals got nothing | ${pct(s.curve.lateThirdGotNothingPct)} | 0% (arrival order plays no part) |`);
console.log(`| Crowd's price ÷ the fair (clearing) price | ${r2(s.curve.crowdPaysTimesFair.median)}× (${r2(s.curve.crowdPaysTimesFair.p10)}–${r2(s.curve.crowdPaysTimesFair.p90)}×) | 1× |`);
